### ISSUE TITLE
能分享一下你签名算法的服务器吗，实在抢不到菜了

### ISSUE THREAD

**Issue by hhh-xiao** [iiwen/dingdong-pro#1]

**Comment by iiwen** [comment]
可以去用GO版本的，只要一天准备一个号就好了。
很无奈，算法不是我写的，要遵守Runc的规定……
前面我直接把我那个仓库删了，后面这个仓库有人关注的话我就更新渠道版，可以抢到的

**Comment by hhh-xiao** [comment]
好吧，GO版本的不好使，用新号测试过了也不行。手动几天了也抢不到

**Comment by iiwen** [comment]
> 好吧，GO版本的不好使，用新号测试过了也不行。手动几天了也抢不到

目前不考虑，如果有能力可以修改GO版本参数防封号
