### ISSUE TITLE
算发布了吗？感觉不太像 readme还没更新

### ISSUE THREAD

**Issue by Izzln** [iiwen/dingdong-pro#4]

**Comment by iiwen** [comment]
不好意思，叮咚接口在今天中午进行了更新，对参数要求变了，我开始适配了

**Comment by Izzln** [comment]
> 不好意思，叮咚接口在今天中午进行了更新，对参数要求变了，我开始适配了

没关系不急 能更新就好T_T 手冲两天啥也没有抢到 runc停了后DD也没变好哇

**Comment by huang111210** [comment]
> 不好意思，叮咚接口在今天中午进行了更新，对参数要求变了，我开始适配了
请问一下今天中午叮咚更新了哪些参数？方便说一下吗？

**Comment by iiwen** [comment]
> > 请问一下今天中午叮咚更新了哪些参数？方便说一下吗？

加强了校验，原生版参数几乎全校验，渠道版目前还好
