### ISSUE TITLE
高峰期报错

### ISSUE THREAD

**Issue by brightyf88** [iiwen/dingdong-pro#7]
大佬：早上6点提交订单失败.
提示：提交订单失败,当前下单总金额：*** 失败:前方拥挤，请稍后再试...

是不是小程序高峰期不能下单？

**Comment by iiwen** [comment]
今日很多人失效，前面两周正常，抱歉

**Comment by iiwen** [comment]
正在修复，暂且下架文件

**Comment by brightyf88** [comment]
今天8点30又成功了
